package com.earthscan.auth.mapper;

import com.earthscan.auth.domain.User;
import com.earthscan.auth.dto.UserResponse;
import java.util.List;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Entity-to-DTO mapping for {@link User}. <strong>Generated by MapStruct at compile time.</strong>
 *
 * <p>Replaces the static {@code UserResponse.from(user)} factory. Three things improve:</p>
 * <ul>
 *   <li><strong>Testability.</strong> A static method cannot be substituted; an injected mapper can,
 *       so a service test can assert mapping behaviour independently.</li>
 *   <li><strong>Compile-time safety.</strong> With {@code unmappedTargetPolicy=ERROR} set in the
 *       parent POM, adding a field to {@code UserResponse} and forgetting to populate it is a build
 *       failure. The hand-written factory would have compiled and returned null.</li>
 *   <li><strong>No reflection.</strong> MapStruct generates plain Java, unlike a runtime mapper such
 *       as ModelMapper, so there is no per-call reflection cost and the generated source is
 *       readable in {@code target/generated-sources}.</li>
 * </ul>
 *
 * <p>{@code componentModel} is {@code spring} globally via a compiler arg, so the generated
 * implementation is a {@code @Component} and injects normally.</p>
 */
@Mapper
public interface UserMapper {

    /**
     * Maps a user to its API projection.
     *
     * <p>{@code role} is mapped from {@code primaryRoleDisplayName} rather than from the roles
     * collection, because the React client stores and compares the display form ("Land Buyer") while
     * the database and the JWT carry the canonical form (LAND_BUYER).</p>
     */
    @Mapping(target = "role", source = "primaryRoleDisplayName")
    UserResponse toResponse(User user);

    List<UserResponse> toResponseList(List<User> users);
}
